spring:
  application:
    name: yyzx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yyzxl
    username: root
    password: myr628304
  jackson:
    time-zone: GMT+8

server:
  # 修改端口号
  port: 8080

# mybatis-plus 配置
mybatis-plus:
  # type handler
  type-handlers-package: com.gzc.handler
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    #  返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名
    map-underscore-to-camel-case: false
  # 别名
  type-aliases-package: com.htu.yyzx.model.entity

# 接口文档配置
knife4j:
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.gzc.controller
  enable: true
    设置为true以启用Knife4j增强功能,这将再应用程序中启用Knife4j UI

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
# 对象存储
# todo 需替换配置
minio:
  # MinIO服务的地址
  url: http://192.168.40.9:9000
  # MinIO的访问密钥
  accessKey: 7UsU8nUwFkjmwC3ByXdb
  # MinIO的密钥
  secretKey: XCvh6PkO7zIXH8256SzrK4Tl7Cuv5A1yKPdj5d8I
  # 默认的存储桶名称
  bucketName: gzc


